monolog:
    channels:
        - app
        - security
        - database
        - request

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        
        # Handler específico para erros
        error:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.error.log"
            level: error
            channels: ["!event"]
            max_files: 30

        # Handler para segurança
        security:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.security.log"
            level: warning
            channels: ["security"]
            max_files: 30

        # Handler para banco de dados
        database:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.database.log"
            level: warning
            channels: ["database"]
            max_files: 30

        # Handler para requests
        request:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.request.log"
            level: info
            channels: ["request"]
            max_files: 7
